name: form_builder_image_picker
description: Images picker field for FlutterFormBuilder. Get images from gallery or camera
version: 4.4.0
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_image_picker
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_image_picker/issues
homepage: https://github.com/flutter-form-builder-ecosystem
funding: 
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.1.0
  async: ^2.13.0
  image_picker: ^1.1.2
  wechat_camera_picker: ^4.3.4

dev_dependencies:
  flutter_lints: ">=6.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: